# Generated by Django 2.1.7 on 2019-03-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190320_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='core.Address'),
        ),
    ]
