# Generated by Django 2.1.7 on 2019-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190320_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastelIDProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastel_id', models.CharField(max_length=512, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
